### PR TITLE
Made some code-readability changes

### PR DESCRIPTION
**Pull request by connorwillchris**

### CODE REVIEW

**Comment by connorwillchris** [comment]
Made some basic code edits. More edits to come soon!

**Comment by dajinkosa** [comment]
Holy shit I didn't expect a person to be interested in a project i mostly abandoned like a year ago

I used the unorthodox symbol because it's quite literally only used in old electrical standards afaik (at the time i thought it was entirely unknown)

**Comment by connorwillchris** [comment]
Okay gotcha, but it's not a common practice in software, since the A and alpha-symbol are practically identical on QWERTY keyboards. Also, mind explaining how you set up the GUI using QT? Is there an application used to design QT applications via the QT xml-like language I found in Main.ui file?

**Comment by dajinkosa** [comment]
Qt designer, which is typically shipped as part of Qt creator but is actually a standalone software you can get
iirc there's a way to get it with pip, don't remember exactly
But basically, p much most important things are in the main.ui

**Pull request closed without merging**
